version: '3.1'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${USERNAME}
            - POSTGRES_PASSWORD=${PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - '5432:5432'