CREATE TABLE employees
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login     text NOT NULL,
    password text NOT NULL,
    UNIQUE (login)
);

CREATE TABLE drones
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    charge int not null default 100,
    capacity int not null,
    distance int not null,
    type text not null,
    status text not null default 'READY',
    image bytea
);



CREATE TABLE orders
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address_delivery text NOT NULL,
    status text not null default 'GOING',
    arrival_date timestamp not null
);

CREATE TABLE order_items
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT not null ,
    name text not null,
    count int not null,
    price float not null,
    weight int not null,
    FOREIGN KEY(order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE TABLE in_delivery
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT not null,
    drone_id BIGINT not null,
    location_x float not null,
    location_y float not null
);
